# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fd3f081a50da66e3419e1ed20d09fec1b4ddd897360c552916ce7497b76fdb332f7649dd5664198a0e5b318538f980ecae5b52414ada29560429f6237cec532

test:
  secret_key_base: 7e7c928dc1ab5515897991817aeca76260dc0229220ce767d08b7f0b07fb15f2325ea243fcb0a89b6f1d79e2c4f1d5b28c06875d402deb94445799aaf427f649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
